export const SET_TEMPLATE = 'SET_TEMPLATE'
export const SET_INTRO_DATA = 'SET_INTRO_DATA'
export const SET_EXPERIENCE_DATA = 'SET_EXPERIENCE_DATA'
export const SET_STEP_DATA = 'SET_STEP_DATA'

export const UPDATE_CURRENT_STEP = 'UPDATE_CURRENT_STEP'
export const ADD_STEP = 'ADD_STEP'
export const DELETE_STEP = 'DELETE_STEP'

export const SHOW_SCENE_SELECTOR = 'SHOW_SCENE_SELECTOR'